server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: broker-demo-group
      auto-offset-reset: earliest
      enable-auto-commit: false
    listener:
      ack-mode: manual

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  data:
    redis:
      host: localhost
      port: 6379

demo:
  kafka:
    topic: demo-topic
  rabbitmq:
    queue: demo-queue
  redis:
    channel: demo-channel

